### ISSUE TITLE
Adjust ec consumption based on flux output

### ISSUE THREAD

**Issue by alexandruast** [MOARdV/AviationLights#13]
EC consumption should properly reflect adjustments made in energy output.

**Comment by MOARdV** [comment]
The least impactful way to apply the change is to scale EC based on intensity - would it be a cubic relationship?  (2 x I = 8 x EC, for instance)

**Comment by alexandruast** [comment]
It's an inverse square relationship, Intensity = 1/d^2.
But ANY implementation is better than nothing :)
Also, decreasing the max. allowable intensity would also be great, it's currently overpowered.

**Comment by MOARdV** [comment]
Unity intensity has nothing to do with distance.  In Unity terms, which are the terms I'm using, intensity is a relative measure of how bright a given light is.  A light with an intensity of 1.0 has twice the perceived brightness as a light of intensity 0.5 at the same distance.  If I double the brightness of the light, does that require 2x the EC?  4x?  8x?  I am not implementing physically-based lighting for the aviation lights mod, as I stated in the other feature request you had submitted.  If there isn't a simple relationship between EC and intensity (in the Unity definition of intensity), then I won't bother changing EC consumption.

I don't see a reason to artificially limit the intensity, since different players have different play styles, and someone might find absurdly high, physically questionable values useful for a particular application.

**Comment by alexandruast** [comment]
In this case(unity), we can assume that the distance is constant from a measuring perspective, so for each unit of brightness, the ec requirement is brightness^2.
