### ISSUE TITLE
Implement more accurate energy model for lights

### ISSUE THREAD

**Issue by alexandruast** [MOARdV/AviationLights#14]
Intensity measures the wave energy, while brightness measures the energy AND wavelength.
Intensity and brightness should be on the same slider, or at least coupled in some way.

**Comment by MOARdV** [comment]
Intensity as applied here is the intensity field found in Unity lights.  The Unity light model follows a common standard found in video game engines - there are three values describing the three color channels, and a value describing the maximum distance from the source where the light may contribute illumination.  Unity also includes a separate intensity parameter which effectively adjusts the brightness of the light without affecting the hue.  Aviation Lights exposes these values directly to the players, allowing them to fine tune and tweak light settings as desired.

I see a couple of ways to couple intensity and hue.  I can keep the RGB sliders, but use denormalized values internally so I can extract the intensity value from the RGB value, or I can use something like a HSV color model.  Either approach requires me to reimplement that feature. Since the Aviation Lights are primarily a decorative element, I don't see enough value added to the mod over what it currently has based on the time required to implement and test it.
